#VERSION
#version: '3.7'

#SERVICIOS
services:

  #FRONT-END
  angular-service:
    container_name: front-whisker
    build: ./Frontend-WhiskerWatch
    ports:
      - "4200:4200"
    depends_on:
      - back
  # BACK-END
  back:
    build: ./KtorApi-WhiskerWatch
    container_name: api-whisker
    ports:
      - "6969:6969"
      - "6963:6963"
    expose:
      - 6969
      - 6963
    depends_on:
      - mongo-express
      - mongodb-server
    networks:
      - mongo-network

  # MONGO DB
  mongodb-server:
    image: mongo
    container_name: mongo-server
    ports:
      - "27017:27017"
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: test
    command: --auth
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mongo-vol:/data/db
    networks:
      - mongo-network
    # restart: always

  # MONGO EXPRESS
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    networks:
      - mongo-network
    depends_on:
      - mongodb-server
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopass
      ME_CONFIG_MONGODB_SERVER: mongodb-server
    restart: unless-stopped

# VOLUMENES
volumes:
  mongo-vol:

# RED
networks:
  mongo-network:
    driver: bridge


